# Generated by Django 4.1.3 on 2022-11-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_location_user_avatar_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(choices=[("M", "남성"), ("F", "여성")], max_length=1),
        ),
    ]
