# Generated by Django 4.1.3 on 2022-11-27 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator("^010[1-9]\\d{3}\\d{4}$")
                ],
            ),
        ),
    ]
