# Generated by Django 4.1.3 on 2022-11-28 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower_set",
            field=models.ManyToManyField(
                related_name="accounts_follower_set", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="following_set",
            field=models.ManyToManyField(
                related_name="accounts_following_set", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
